# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://ep-empty-snowflake-a1mipsm3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_sFid7Gfq8DcS
    driver-class-name: org.postgresql.Driver
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    com.chitchat.backend: DEBUG
    # Keep some debugging for development but reduce noise
    org.springframework.security: INFO
    # Hibernate logging - controlled for development
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    # WebSocket and messaging logging - reduced even in dev
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
    org.springframework.messaging.simp: INFO
    org.springframework.messaging.handler: INFO
    # Tomcat WebSocket logging
    org.apache.tomcat.websocket: INFO
    
jwt:
  secret-key: "dev-secret-key-for-development-only-not-for-production"
  expiration: 3600000  # 1 hour
  
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
gemini:
  api-key: "AIzaSyCcTP3r-KBxe3MwVKxW2opivTBZcu-jXuE"
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
  model: "gemini-1.5-flash"
