server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-empty-snowflake-a1mipsm3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_sFid7Gfq8DcS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

jwt:
  secret-key: "dGhpcyBpcyBhIHNlY3VyZSBqd3Qgc2VjcmV0IGtleSBmb3IgY2hpdGNoYXQgYXBwbGljYXRpb24gd2l0aCBzdWZmaWNpZW50IGxlbmd0aA=="
  expiration: 3600000  # 1 hour

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"

gemini:
  api-key: "AIzaSyCcTP3r-KBxe3MwVKxW2opivTBZcu-jXuE"
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
  model: "gemini-2.0-flash"

# File Upload Configuration
file:
  upload-dir: uploads

# Logging Configuration
logging:
  level:
    root: INFO
    com.chitchat.backend: INFO
    # Hibernate logging - reduced verbosity
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    org.hibernate.type.descriptor.sql: WARN
    # WebSocket and messaging logging - reduced verbosity
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
    org.springframework.messaging.simp: INFO
    org.springframework.messaging.handler: INFO
    # Spring framework logging
    org.springframework.web: WARN
    org.springframework.security: WARN
    # Tomcat WebSocket logging
    org.apache.tomcat.websocket: INFO
    # Other infrastructure logging
    reactor.netty: WARN
    org.apache.coyote: WARN
    org.apache.tomcat: WARN
    org.springframework.web.context.request.async: ERROR
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){faint} %clr(%-40.40logger{36}){cyan} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
